### PR TITLE
Fixed a regression that has caused `machine.getInitialState(value)` to not follow always transitions correctly

### LINKED ISSUE #3544: Bug: eventless transitions in parallel states not taken anymore when starting interpreter from given state
### Description

Eventless transitions in parallel state are not taken anymore when interpreter is started from a given state.

### Expected result

Eventless transitions should always be taken.

For example, in the linked reproduction sandbox, the expected result is:
```
state.value == {"b":{"x":"bar","y":{}}} 
```

This is the result obtained with xstate version < 4.33.0

### Actual result

The eventless transition in example is not taken anymore with xstate version >= 4.33.0.

Instead, we get:

```
state.value == {"b":{"x":"foo","y":{}}} 
```

### Reproduction

https://codesandbox.io/s/affectionate-thunder-esq8rn?file=/src/index.js

### Additional context

It looks like a regression introduced in version 4.33.0.

### PR DESCRIPTION
**Pull request by Andarist**
fixes #3544

### CODE REVIEW

File: packages/core/src/StateNode.ts [hunk 1]
```diff
@@ -1661,7 +1664,7 @@ class StateNode<
     return this.resolveTransition(
       {
         configuration,
-        entrySet: [...configuration],
+        entrySet: configuration,
```
Comment (Andarist) [inline packages/core/src/StateNode.ts:1667]: It brings back a shared reference being used for both `entrySet` and for `configuration`. This is somewhat dangerous but I just hope that v5 algorithm works better in this regard.

It has been like that for a long time, I've "fixed" this problem [here](https://github.com/statelyai/xstate/pull/3422/files#r905127802) but that accidentally caused the mentioned regression. So now instead of copying the reference, I make sure that we don't push items to the `entrySet` that are already there:
https://github.com/statelyai/xstate/pull/3599/files#diff-7f553f4d4c285f1c05cced2e979c5b957d8884e39e74cc6797b32c63a0be7e7aR1015

File: packages/core/test/rehydration.test.ts [hunk 2]
```diff
@@ -98,4 +98,21 @@ describe('rehydration', () => {
...
+        initial: 'a',
+        states: {
+          a: {
+            always: [{ target: 'b' }]
+          },
+          b: {}
+        }
+      });
+
+      const service = interpret(machine).start(machine.getInitialState('a'));
```
Comment (Andarist) [inline packages/core/test/rehydration.test.ts:114]: Interestingly, this doesn't follow always transitions:
```diff
-      const service = interpret(machine).start(machine.getInitialState('a'));
+      const service = interpret(machine).start('a');
```

I would consider this to be a bug too but it just never worked correctly and I don't think it's necessary to fix this in v4.

**Review by davidkpiano — APPROVED** [review]
